### ISSUE TITLE
Training spikes with FSDP

### ISSUE THREAD

**Issue by ShivanshuPurohit** [google/maxtext#16]
I've noticed that training is really unstable with FSDP. My config is a 7.5B model with 3xv4-384, and can be replicated with configs in my fork https://github.com/ShivanshuPurohit/maxtext/blob/training-spikes/MaxText/configs/3xv4-384.sh

<img width="379" alt="image" src="https://user-images.githubusercontent.com/42869065/234543025-096e4611-e72f-44d5-8e24-3e65d789b26a.png">
here's an example run with my config.

**Comment by rwitten** [comment]
I'm sorry for your loss. We will respond back with suggestions in the next day or two.

**Comment by gobbleturk** [comment]
This is fixed by changing Adam beta from 0.999 to 0.95 in this [PR](https://github.com/google/maxtext/pull/17)

Before and After runs on a 17B model
Before Adam beta2=0.999: 
![Pre-beta-instability](https://user-images.githubusercontent.com/51136315/234967068-4b03a1d7-b862-4b83-8151-6f61a65a327f.png)

After Adam beta2=0.95: 
![post-beta-stability](https://user-images.githubusercontent.com/51136315/234967139-05b46ab3-d206-459a-b372-4c404a1c1454.png)
