### ISSUE TITLE
README is missing instructions for `dataset_path` flag

### ISSUE THREAD

**Issue by yashs97** [google/maxtext#63]
Since `dataset_path` is a required flag for train.py after https://github.com/google/maxtext/pull/61, please consider adding instructions for it in the Quick Experiments Section on Multiple Slices and other such section of the README.

Thank you!

**Comment by priyanka-ganesha** [comment]
Thank you! I have clarified some instructions in the error message in #65. Instructions to set config values for `base_output_directory` and `dataset_path` are on the README in the [Getting Started: Download Dataset and Configure](https://github.com/google/maxtext#getting-started-download-dataset-and-configure) section, step 3. Ideally, it will be set in the config file for the sake of simplicity, instead of being passed in as a CLI flag.
